[providers.age]
type = "age"
recipients = ["age1qx2dpd4rkc72f62898v73hvxj8325rm6tp70tyjugkrzy0qy537sqz08wq"]
key_file = "~/.config/fnox/age.txt"

[secrets]
GITHUB_CLIENT_SECRET= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweENCZk9lSkpNMGNvaFpQUG5sakxZcG5yVE1ZV2ZUWjVhdDVnWG9uaEFZClowdUxjV3VWSi83eGJIdmVZMDhMM3Vna3MyZGp0N1ZhU2hKcVBWQ3UrNEEKLT4gP3R9LWdyZWFzZSBAOz0tcmNeaCBUVzAlIEkKdlM3N2VWRVUrb1RydWtIaEtlUGhCcG5zV0V1WUQ0UjhuSzlnN2lDUU84bnFra3gxc3Zwb1kyWU16M2o0WStHagpLZmJNSno3NDdJWWhzaXdEb1ZsYStUb2RWVFBxdTBzWlNHLzdTVWllZlpWanhUVDdRcTNBL1ZrCi0tLSA4S0laa1IyMC8rYkNzQTQ0cjdCRUd5U2JNOWp0dUpPTmRUYWFUTXJSZTJ3CuyVxhb32zFRwzTs4Q0f1xUzgVDcg53zl9fhhdCrZ0b9aTV0g/2ZhJWRGGUpYGtqK9KVH2Oy2jn3rbtSbRYJS0cUnDFNOnd/4w==", description = "gheart GitHub OAuth app client secret" }
